resources:
  - ../../base

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization










































patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
