name: Scale Down
on: workflow_dispatch

permissions:
  contents: write

jobs:
  scale-down:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Add scale-down patch
        run: |
          for FILE in k8s_kustomize/overlays/development/kustomization.yaml k8s_kustomize/overlays/staging/kustomization.yaml; do
            if ! grep -q 'value: 0' "$FILE"; then
              echo "Adding scale-down patch to $FILE"
              echo -e "\npatches:\n  - target:\n      kind: Deployment\n    patch: |-\n      - op: replace\n        path: /spec/replicas\n        value: 0" >> "$FILE"
            fi
          done

      - name: Update README badges
        run: |
          sed -i 's|![Dev Status](.status/scale_status_dev_up.svg)|![Dev Status](.status/scale_status_dev_down.svg)|g' README.md
          sed -i 's|![Staging Status](.status/scale_status_staging_up.svg)|![Staging Status](.status/scale_status_staging_down.svg)|g' README.md

      - name: Generate Down badges
        run: |
          python3 ./.status/generate_badge.py \
            --left-text "Aurora Dev Status" \
            --right-text "Down" \
            --left-color "#4D4D4D" \
            --right-color "#FF451D" \
            --output-path "./.status/scale_status_dev_down.svg"

          python3 ./.status/generate_badge.py \
            --left-text "Aurora Staging Status" \
            --right-text "Down" \
            --left-color "#4D4D4D" \
            --right-color "#FF451D" \
            --output-path "./.status/scale_status_staging_down.svg"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s_kustomize/overlays/development/kustomization.yaml
          git add k8s_kustomize/overlays/staging/kustomization.yaml
          git add ./.status/scale_status_dev_up_down.svg
          git add ./.status/scale_status_staging_up_down.svg
          git commit -m "Scale down deployments and update badges for development and staging" || echo "No changes to commit"
          git push
