name: Scale Up
on:
  workflow_call:
    inputs:
      AuthorName:
        required: false
        type: string
    secrets: {}
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scale-up:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Remove scale-down patch
        run: |
          for FILE in k8s_kustomize/overlays/development/kustomization.yaml k8s_kustomize/overlays/staging/kustomization.yaml; do
            if grep -q 'value: 0' "$FILE"; then
              echo "Removing scale-down patch from $FILE"
              sed -i '/patches:/,/value: 0/d' "$FILE"
            fi
          done

      - name: Update README badges
        run: |
          awk '{gsub(/!\[Dev Status]\(https:\/\/img.shields.io\/badge\/Aurora_Dev_Status-Down-red\)/, "![Dev Status](https://img.shields.io/badge/Aurora_Dev_Status-Up-green)"); print}' README.md > tmp && mv tmp README.md
          awk '{gsub(/!\[Staging Status]\(https:\/\/img.shields.io\/badge\/Aurora_Staging_Status-Down-red\)/, "![Staging Status](https://img.shields.io/badge/Aurora_Staging_Status-Up-green)"); print}' README.md > tmp && mv tmp README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git add k8s_kustomize/overlays/development/kustomization.yaml
          git add k8s_kustomize/overlays/staging/kustomization.yaml
          git add ./.status/scale_status_dev_up.svg
          git add ./.status/scale_status_staging_up.svg
          git commit -m "Scale up deployments and update badges for development and staging"
          git push
