name: Scale Up
on: workflow_dispatch

permissions:
  contents: write

jobs:
  scale-up:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Remove scale-down patch
        run: |
          for FILE in k8s_kustomize/overlays/development/kustomization.yaml k8s_kustomize/overlays/staging/kustomization.yaml; do
            if grep -q 'value: 0' "$FILE"; then
              echo "Removing scale-down patch from $FILE"
              sed -i '/patches:/,/value: 0/d' "$FILE"
            fi
          done

      - name: Update README badges
        run: |
          sed -i 's|![Dev Status](.status/scale_status_dev_down.svg)|![Dev Status](.status/scale_status_dev_up.svg)|g' README.md
          sed -i 's|![Staging Status](.status/scale_status_staging_down.svg)|![Staging Status](.status/scale_status_staging_up.svg)|g' README.md


      - name: Generate Up badges
        run: |
          python3 ./.status/generate_badge.py \
            --left-text "Aurora Dev Status" \
            --right-text "Up" \
            --left-color "#4D4D4D" \
            --right-color "#44CC11" \
            --output-path "./.status/scale_status_dev_up.svg"

          python3 ./.status/generate_badge.py \
            --left-text "Aurora Staging Status" \
            --right-text "Up" \
            --left-color "#4D4D4D" \
            --right-color "#44CC11" \
            --output-path "./.status/scale_status_staging_up.svg"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s_kustomize/overlays/development/kustomization.yaml
          git add k8s_kustomize/overlays/staging/kustomization.yaml
          git add ./.status/scale_status_dev_up.svg
          git add ./.status/scale_status_staging_up.svg
          git commit -m "Scale up deployments and update badges for development and staging"
          git push
