name: Scale Up
on: workflow_dispatch

permissions:
  contents: write

jobs:
  scale-up:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Remove scale-down patch if present
        run: |
          for FILE in \
            k8s_kustomize/overlays/development/kustomization.yaml \
            k8s_kustomize/overlays/staging/kustomization.yaml; do

            if grep -q 'value: 0' "$FILE"; then
              echo "Removing scale-down patch from $FILE"
              # Remove the entire 'patches' section starting from 'patches:' to the end
              sed -i '/patches:/,$d' "$FILE"
            else
              echo "No scale-down patch found in $FILE"
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s_kustomize/overlays/development/kustomization.yaml
          git add k8s_kustomize/overlays/staging/kustomization.yaml
          git commit -m "Scale up deployment replicas for development and staging"
          git push
